// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.gamegateway.domain.ws.req.socketrequest

@SerialVersionUID(0L)
final case class SocketRequest(
    p1: String = "",
    p2: String = "",
    p3: String = "",
    p4: String = "",
    p5: String = "",
    p6: String = "",
    p7: String = "",
    p8: String = "",
    p9: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[SocketRequest] with com.trueaccord.lenses.Updatable[SocketRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (p1 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, p1) }
      if (p2 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, p2) }
      if (p3 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, p3) }
      if (p4 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, p4) }
      if (p5 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, p5) }
      if (p6 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, p6) }
      if (p7 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, p7) }
      if (p8 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, p8) }
      if (p9 != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, p9) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = p1
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = p2
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = p3
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = p4
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = p5
        if (__v != "") {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = p6
        if (__v != "") {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = p7
        if (__v != "") {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = p8
        if (__v != "") {
          _output__.writeString(8, __v)
        }
      };
      {
        val __v = p9
        if (__v != "") {
          _output__.writeString(9, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest = {
      var __p1 = this.p1
      var __p2 = this.p2
      var __p3 = this.p3
      var __p4 = this.p4
      var __p5 = this.p5
      var __p6 = this.p6
      var __p7 = this.p7
      var __p8 = this.p8
      var __p9 = this.p9
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __p1 = _input__.readString()
          case 18 =>
            __p2 = _input__.readString()
          case 26 =>
            __p3 = _input__.readString()
          case 34 =>
            __p4 = _input__.readString()
          case 42 =>
            __p5 = _input__.readString()
          case 50 =>
            __p6 = _input__.readString()
          case 58 =>
            __p7 = _input__.readString()
          case 66 =>
            __p8 = _input__.readString()
          case 74 =>
            __p9 = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest(
          p1 = __p1,
          p2 = __p2,
          p3 = __p3,
          p4 = __p4,
          p5 = __p5,
          p6 = __p6,
          p7 = __p7,
          p8 = __p8,
          p9 = __p9
      )
    }
    def withP1(__v: String): SocketRequest = copy(p1 = __v)
    def withP2(__v: String): SocketRequest = copy(p2 = __v)
    def withP3(__v: String): SocketRequest = copy(p3 = __v)
    def withP4(__v: String): SocketRequest = copy(p4 = __v)
    def withP5(__v: String): SocketRequest = copy(p5 = __v)
    def withP6(__v: String): SocketRequest = copy(p6 = __v)
    def withP7(__v: String): SocketRequest = copy(p7 = __v)
    def withP8(__v: String): SocketRequest = copy(p8 = __v)
    def withP9(__v: String): SocketRequest = copy(p9 = __v)
    def getField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = p1
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = p2
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = p3
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = p4
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = p5
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = p6
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = p7
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = p8
          if (__t != "") __t else null
        }
        case 9 => {
          val __t = p9
          if (__t != "") __t else null
        }
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest
}

object SocketRequest extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(4), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(5), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(6), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(7), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(8), "").asInstanceOf[String]
    )
  }
  def descriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SocketrequestProto.descriptor.getMessageTypes.get(0)
  def messageCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest(
  )
  implicit class SocketRequestLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.jxjxgo.gamegateway.domain.ws.req.socketrequest.SocketRequest](_l) {
    def p1: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p1)((c_, f_) => c_.copy(p1 = f_))
    def p2: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p2)((c_, f_) => c_.copy(p2 = f_))
    def p3: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p3)((c_, f_) => c_.copy(p3 = f_))
    def p4: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p4)((c_, f_) => c_.copy(p4 = f_))
    def p5: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p5)((c_, f_) => c_.copy(p5 = f_))
    def p6: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p6)((c_, f_) => c_.copy(p6 = f_))
    def p7: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p7)((c_, f_) => c_.copy(p7 = f_))
    def p8: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p8)((c_, f_) => c_.copy(p8 = f_))
    def p9: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.p9)((c_, f_) => c_.copy(p9 = f_))
  }
  final val P1_FIELD_NUMBER = 1
  final val P2_FIELD_NUMBER = 2
  final val P3_FIELD_NUMBER = 3
  final val P4_FIELD_NUMBER = 4
  final val P5_FIELD_NUMBER = 5
  final val P6_FIELD_NUMBER = 6
  final val P7_FIELD_NUMBER = 7
  final val P8_FIELD_NUMBER = 8
  final val P9_FIELD_NUMBER = 9
}
