// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.gamegateway.domain.ws.req.socketrequest

object SocketrequestProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChdyZXEvc29ja2V0cmVxdWVzdC5wcm90byKfAQoNU29ja2V0UmVxdWVzdBIOCgJwMRgBIAEoCVICcDESDgoCcDIYAiABKAlSA
  nAyEg4KAnAzGAMgASgJUgJwMxIOCgJwNBgEIAEoCVICcDQSDgoCcDUYBSABKAlSAnA1Eg4KAnA2GAYgASgJUgJwNhIOCgJwNxgHI
  AEoCVICcDcSDgoCcDgYCCABKAlSAnA4Eg4KAnA5GAkgASgJUgJwOUImCiRjb20uanhqeGdvLmdhbWVnYXRld2F5LmRvbWFpbi53c
  y5yZXFiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}