// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.gamegateway.domain.ws.resp.socketresponse

object SocketresponseProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChhyZXEvc29ja2V0cmVzcG9uc2UucHJvdG8ioAEKDlNvY2tldFJlc3BvbnNlEg4KAnAxGAEgASgJUgJwMRIOCgJwMhgCIAEoC
  VICcDISDgoCcDMYAyABKAlSAnAzEg4KAnA0GAQgASgJUgJwNBIOCgJwNRgFIAEoCVICcDUSDgoCcDYYBiABKAlSAnA2Eg4KAnA3G
  AcgASgJUgJwNxIOCgJwOBgIIAEoCVICcDgSDgoCcDkYCSABKAlSAnA5QicKJWNvbS5qeGp4Z28uZ2FtZWdhdGV3YXkuZG9tYWluL
  ndzLnJlc3BiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}